### ISSUE TITLE
Question about S2S being unspecified

### ISSUE THREAD

**Issue by hhirtz** [ircdocs/modern-irc#75] opened 2019-05-28 18:24 UTC
Hi Daniel!

> https://modern.ircdocs.horse/#server-to-server-protocol-structure
>
>Various server to server (S2S) protocols have been defined over the years, with TS6 and P10 among the most popular (both based on the client-server protocol as described below). However, with the fragmented nature of server implementations, features, network designs and S2S protocols, right now it is impossible to define a single standard server to server protocol.

Shouldn't this paragraph be updated since there is a RFC for the S2S protocol?

https://tools.ietf.org/html/rfc2813.html

Or is it that implementations don't follow this RFC?

**Comment by DanielOaks** [comment] 2019-05-29 01:04
Hey mate! Yeah the issue is the protocol described by that RFC is no longer used. The original implementation (irc2) might follow it, but these days servers generally implement either the TimeStamp/TSora family of protocols (ref [1](https://github.com/grawity/irc-docs/blob/master/server/espel-tsora/Undernet-TS.txt)) or the p10 family of protocols (refs for both of these can be found [here](https://github.com/grawity/irc-docs/tree/master/server) under the `ts*` and `p10*` textfiles).

Both TS and P10 are _families_ of S2S protocols because every server tends to have its own special fork and changes of the base protocol, which is why while the above references are good guides (and both these S2S protocols are originally based on the original S2S proto described in RFC1459/2813), they don't describe how to interact perfectly with every server implementing it. Looking into services packages (anope/atheme, and [pylink](https://github.com/jlu5/PyLink/tree/master/protocols)) gives more detail about how to talk to a variety of different servers.

In addition to those two families, InspIRCd has its own separate S2S protocol, though I can't say for sure whether they based theirs on that original one or went with a more from-scratch approach. And other servers may do things an entirely different way.

For what it's worth some attempts have been made to do things like explore meshy or mesh-based architectures, other generally more resilient architectures and etc. Though it's a little older these days, [this article](http://kaniini.dereferenced.org/2015/04/21/robustirc-isnt.html) has some interesting info and opinions around using Raft consensus methods to handle S2S in a less-netsplitty way, and how it differs from traditional IRC's availability.

---------

In general, end-user IRC software doesn't really need to do anything with the S2S side of IRC. And servers can do whatever works for them, even forgoing an S2S protocol entirely if they want to (which is what [my server](https://github.com/oragono/oragono) that provides 'services' in a different way does).

I've got a blog post [over here](https://blog.danieloaks.net/irc-server-protocols-and-standardisation-c66070a456a2) that goes deeper into server protocols and standardisation questions if you're after a read, but I hope that answers some questions anyways. Thanks for making the issue, always happy to help and chat!

**Comment by hhirtz** [comment] 2019-05-29 10:10
I see, so implementations are not meant to be used with other impls in the same network. Maybe this should be more clear in the specification. I'd be happy to make a PR for that!

Thank you for the links and articles, that's a lot of things to look into.

> In general, end-user IRC software doesn't really need to do anything with the S2S side of IRC. And for servers it's not required, they can do whatever works for them – even forgoing an S2S protocol entirely if they want to (which is what my server that provides 'services' in a different way does).

Do you mean other servers connect to each other as services?

**Comment by DanielOaks** [comment] 2019-05-29 13:42
Ah for sure, if you'd like to throw some language into a PR I'd definitely be up for it! Though I can be a bit pedantic when it comes to wording, so don't stress too much if I merge it and then do some editing on top~

> Do you mean other servers connect to each other as services?

Yeah kinda. For most IRC servers, 'services' (account registration, channel registration, etc) is provided by an external piece of software like Atheme or Anope that connects to the network using the native S2S protocol of whatever server it's connecting to (for example, Anope has different protocol modules for [Bahamut, Charybdis, Hybrid, InspIRCd, Unreal](https://github.com/anope/anope/tree/2.0/modules/protocol) and the like because each one uses a different S2S protocol). For example, if you connect Anope to InspIRCd, then InspIRCd will see it as another regular InspIRCd server (with maybe some extra features enabled and more permissions/priority than a normal server would get).

Some server software doesn't use a separate piece of software and instead provides account/channel registration services as an in-built part of the IRC server, though this is mostly for servers written from the ground-up and/or ones designed for smaller networks that don't need multiple servers. [Oragono](https://github.com/oragono/oragono)'s a good example of a server that does this, and I know that certain larger servers have at least experimented with providing them natively in this sort of way.

**Comment by hhirtz** [comment] 2019-05-29 15:53
> Ah for sure, if you'd like to throw some language into a PR I'd definitely be up for it! Though I can be a bit pedantic when it comes to wording, so don't stress too much if I merge it and then do some editing on top~

Haha sure I'll take my chances this week end.

> For most IRC servers, 'services' (account registration, channel registration, etc) is provided by an external piece of software like Atheme or Anope that connects to the network using the native S2S protocol of whatever server it's connecting to.

Also just a last question! Does that mean services as defined by RFC2812 (clients that log in via the SERVICE message) are no longer used? I noticed SQUERY and SERVLIST return ERR_UNKNOWNCOMMAND on freenode (running IRCd, the reference implementation?).

Just trying to figure out what to implement in a server, beyond the client protocol, so that it's at least a bit interoperable with other software (even though it's not the end goal). The RFCs mentions services as clients that register via SERVICE, that have access to more information than users, but can't send messages nor join channels. Are those services the one you talk about?

**Comment by DanielOaks** [comment] 2019-05-29 20:36
> Does that mean services as defined by RFC2812 (clients that log in via the SERVICE message) are no longer used?

Yep. I believe that only ircd2 ended up implementing these, nothing else has. You can safely ignore these commands and service clients as defined by the 281* RFCs.

**Comment by progval** [comment] 2021-12-23 21:32
Looks like this is answered, closing.

**Closed by progval** 2021-12-23 21:32 UTC
